FROM python:3.11

EXPOSE 8000

# 安裝所需依賴項
COPY requirements.txt .
RUN pip install -r requirements.txt
    
# 設置專案
RUN mkdir /back_end
COPY ./back_end /back_end

# 設置工作位置
WORKDIR /back_end

# 設置備份資料夾
RUN mkdir /backup

# 設置起始檔
COPY ./startup_backend.sh .

# 因作業系統不同，導致格式不同，需進行格式轉換
RUN sed -i -e 's/\r$//' startup_backend.sh

RUN chmod +x ./startup_backend.sh

# 執行
CMD ["./startup_backend.sh"]