FROM mysql:9.0.1

EXPOSE 3306

# 設置備份資料夾
RUN mkdir /backup

# 設置起始檔
COPY ./init.sql /docker-entrypoint-initdb.d/
COPY ./startup_database.sh .

# 因作業系統不同，導致格式不同，需進行格式轉換
RUN sed -i -e 's/\r$//' startup_database.sh

RUN chmod -x ./startup_database.sh

# 執行
CMD ["./startup_database.sh"]